# Site settings
author: Dan Ste. Marie Jr.
title: The Coding Diaries
header-img: img/home-bg.png
email: dste.mariejr@gmail.com
copyright_name: Dan Ste. Marie Jr.
description: > # this means to ignore newlines until "baseurl:"
  A newbie's journey in coding.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  indiejesus2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
